# Generated by Django 4.0.6 on 2022-07-13 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('linux', models.IntegerField(default=0)),
                ('mac', models.IntegerField(default=0)),
                ('android', models.IntegerField(default=0)),
                ('iphone', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'General OS Analytic',
                'verbose_name_plural': 'General OS Analytics',
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('linux', models.IntegerField(default=0)),
                ('mac', models.IntegerField(default=0)),
                ('android', models.IntegerField(default=0)),
                ('iphone', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
                ('sessionid', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User OS Analytics',
                'verbose_name_plural': 'User OS Analytics',
            },
        ),
        migrations.CreateModel(
            name='UserAnalyticsMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('current_page', models.CharField(max_length=500)),
                ('page_visits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bound_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='extra_analytics.useranalytics')),
            ],
            options={
                'verbose_name': 'Specific Site Analytics',
                'verbose_name_plural': 'Specific Site Analytics',
            },
        ),
    ]
