# Generated by Django 4.0.6 on 2022-07-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=254)),
                ('hits', models.IntegerField(default=0)),
                ('misses', models.IntegerField(default=0)),
                ('times_invalidated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cache Analytics',
                'verbose_name_plural': 'Cache Analytics',
            },
        ),
    ]
