# Generated by Django 4.0.6 on 2022-07-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_analytics', '0002_cacheanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheanalytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
